### ISSUE TITLE
Invalid typed array length in arrayBufferReader Line 12

### ISSUE THREAD

**Issue by BMo-design** [marook/osm-read#34]
Hi,
I want to parse a pbf generated by my geoserver and get a "Invalid typed array length in arrayBufferReader Line 12" the size variable in line 11 is 445776650.

I tried the same with a Mapbox pbf -> same issue.

Any ideas?

**Comment by nrenner** [comment]
osm-read is about parsing the [OSM PBF](http://wiki.openstreetmap.org/wiki/PBF_Format) format, it will not work with the [Mapbox vector tile](https://www.mapbox.com/vector-tiles/specification/) format. Which is also based on Protocol Buffers but has a different structure (I find it very unfortunate that Mapbox has been calling and naming their format pbf too - but seem to switch to using mvt recently).

See https://github.com/mapbox/awesome-vector-tiles for other libraries to use.
