### ISSUE TITLE
Vulnerability in protobuf dependencies

### ISSUE THREAD

**Issue by avengerx** [marook/osm-read#37]
This seems to be already work in progress given a1530bf. Would you please post an update here when the fixed version gets published to npm?

**Comment by lukaselmer** [comment]
@marook what it the reason that the current master branch is not released? Need help?

**Comment by marook** [comment]
i had some issues make it work in the browser again and that exceeded my osm-read timebox. feel free to fix it and i will be happy about a pull request :)
